signal.SIGALRM is not available on this platform
signal.SIGALRM is not available on this platform
  0%|          | 0/500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShuttleChaser\Documents\python_script\LLM\opencompass\opencompass\tasks\openicl_eval.py", line 59, in <module>
    class OpenICLEvalTask(BaseTask):
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 666, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "C:\Users\ShuttleChaser\anaconda3\envs\opencompass\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'OpenICLEvalTask is already registered in task at opencompass.tasks.openicl_eval'
